name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag machine_learning:$(date +%s)

    - name: Run Docker container
      env:
        SAMPLE_PASSWORD: ${{ secrets.SAMPLE_PASSWORD }}
      run: docker run -e SAMPLE_PASSWORD=$SAMPLE_PASSWORD machine_learning:$(date +%s)
